name: push dockerhub
## 参考: https://github.com/docker/build-push-action
on:
  push:
    branches:
      - main # 触发的分支，可以根据需要修改
permissions:
  contents: write

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest
    steps:
      ##### Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      #### Add support for more platforms with QEMU (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      #####  Login to Docker Hub (发布镜像到Docker Hub)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # 需要再 docker hub 中去创建 token,然后填写到secrets中 (docker hub token)
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      ##### 发布镜像
      - name: Build and Push Container image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: qqzsc/windows-font:0.0.1
